### ISSUE TITLE
/vendor/autoload.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by niamrox** [wp-strap/wordpress-plugin-boilerplate#3]
After all step seems there one file is missing. /vendor/autoload.php: failed to open stream: No such file or directory

**Comment by niamrox** [comment]
It makes the whole plugin unusable ! Let me know if I miss anything

**Comment by niamrox** [comment]
Got it "composer dump-autoload"

**Comment by IonTulbure** [comment]
I solved it by running ```composer install```
